apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: 619202462068.dkr.ecr.us-east-2.amazonaws.com/mydockerrepo1:latest
      ports:
        - containerPort: 8080
